export const mapping = [
  {name: "Machine Translation", color: "#8884d8" },
  {name: "Textual entailment", color: "#82ca9d" },
  {name: "Paraphrasing", color: "#1abc9c" },
  {name: "Annotation", color: "#2ecc71" },
  {name: "Language Understanding", color: "#3498db" },
  {name: "Morphological Analysis", color: "#9b59b6" },
  {name: "Word Sense Disambiguation", color: "#34495e" },
  {name: "Native Language Identification", color: "#16a085" },
  {name: "Coreference Resolution", color: "#27ae60" },
  {name: "Language Generation", color: "#2980b9" },
  {name: "Question Answering", color: "#8e44ad" },
  {name: "Syntactic Parsing", color: "#2c3e50" },
  {name: "Semantic Role Labeling", color: "#f1c40f" },
  {name: "Neural Networks", color: "#e67e22" },
  {name: "Information Extraction", color: "#e74c3c" },
  {name: "Named Entity Recognition", color: "#CF3A24" },
  {name: "Summarization", color: "#95a5a6" },
  {name: "Topic Modeling", color: "#f39c12" },
  {name: "Machine translation", color: "#d35400" },
  {name: "Dialogue and interactive systems", color: "#c0392b" },
]
